<a href="https://colab.research.google.com/github/xyhosino/DeepLearning/blob/main/%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0_%E7%AC%AC2%E8%AF%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from keras.datasets import mnist
(x_train_image, y_train_lable), (x_test_image, y_test_lable) = mnist.load_data()
print("数据集张量形状：", x_train_image.shape)
print("第一个数据样本：\n", x_train_image[0])
print("第一数据样本的标签：", y_train_lable[0])

数据集张量形状： (60000, 28, 28)
第一个数据样本：
 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0

In [ ]:
from keras.utils import to_categorical
x_train = x_train_image.reshape(60000,28,28,1)
x_test = x_test_image.reshape(10000,28,28,1)
y_train = to_categorical(y_train_lable,10)
y_test = to_categorical(y_test_lable,10)
print("训练集张量形状：", x_train.shape)
print("第一数据标签：", y_train[0])

训练集张量形状： (60000, 28, 28, 1)
第一数据标签： [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
import numpy as np
x = np.array(5)
print("x的值", x)
print("x的阶", x.ndim)
print("x的数据类型", x.dtype)
print("x的形状", x.shape)

x的值 5
x的阶 0
x的数据类型 int64
x的形状 ()


In [ ]:
n = 0
for gender in [0, 1]:
    n = n + 1
print(n)

2


In [ ]:
import pandas as pd
from keras.datasets import boston_housing
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()
print("x_train的形状：", x_train.shape)
print("x_train中的第一个样本的形状：", x_train[0].shape)
print("y_train的形状：", y_train.shape)
x_test_df = pd.DataFrame(x_test)
y_test_df = pd.DataFrame(y_test)
print(x_test_df.head(100))
print(y_test_df.head(100))

x_train的形状： (404, 13)
x_train中的第一个样本的形状： (13,)
y_train的形状： (404,)
          0     1      2    3      4   ...    8      9     10      11     12
0   18.08460   0.0  18.10  0.0  0.679  ...  24.0  666.0  20.2   27.25  29.05
1    0.12329   0.0  10.01  0.0  0.547  ...   6.0  432.0  17.8  394.95  16.21
2    0.05497   0.0   5.19  0.0  0.515  ...   5.0  224.0  20.2  396.90   9.74
3    1.27346   0.0  19.58  1.0  0.605  ...   5.0  403.0  14.7  338.92   5.50
4    0.07151   0.0   4.49  0.0  0.449  ...   3.0  247.0  18.5  395.15   8.44
..       ...   ...    ...  ...    ...  ...   ...    ...   ...     ...    ...
95   1.65660   0.0  19.58  0.0  0.871  ...   5.0  403.0  14.7  372.80  14.10
96   0.66351  20.0   3.97  0.0  0.647  ...   5.0  264.0  13.0  383.29   7.79
97   3.47428   0.0  18.10  1.0  0.718  ...  24.0  666.0  20.2  354.55   5.29
98   0.07896   0.0  12.83  0.0  0.437  ...   5.0  398.0  18.7  394.92   6.78
99   1.83377   0.0  19.58  1.0  0.605  ...   5.0  403.0  14.7  389.61   1.92

[100 rows

In [ ]:
weight = np.array([1, -1.8, 1, 1, 2])
x = np.array([1, 6, 7, 8, 9])
y_hat_1 = weight.dot(x)
y_hat_2 = x.dot(weight)
y_hat_3 = np.dot(x,weight)
print(y_hat_1, y_hat_2, y_hat_3)

23.2 23.2 23.2


In [ ]:
import numpy as np
array_01 = np.arange(1,5,1)
array_02 = np.linspace(1,5,5)
print(array_01, array_02)
array_03 = np.arange(17)
slice_01 = array_03[0:17:4]
print(array_03)
print(slice_01)

[1 2 3 4] [1. 2. 3. 4. 5.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 0  4  8 12 16]


In [ ]:
array_04 = np.array([[1,2,3],[4,5,6]])
array_04 += 1
print(array_04)
for i in range(array_04.shape[0]):
 for j in range(array_04.shape[1]):
  print(np.sqrt(array_04[i][j]))

[[2 3 4]
 [5 6 7]]
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907


In [ ]:
print(array_04.reshape(3,2))
array_05 = array_04.reshape(3,2)
print(array_05)
array_06 = array_04.T
print(array_06)

[[2 3]
 [4 5]
 [6 7]]
[[2 3]
 [4 5]
 [6 7]]
[[2 5]
 [3 6]
 [4 7]]


In [ ]:
array_07 = np.array([0,1,2])
array_08 = array_07.reshape(3)
array_09 = array_07.reshape(3,1)
print(array_08)
print(array_09)

[0 1 2]
[[0]
 [1]
 [2]]
